name: Deploy React Firebase App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with Firebase Environment Variables
        run: |
          docker build -t pamitha/ctse-assignment1 \
            --build-arg REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} \
            --build-arg REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }} \
            --build-arg REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }} \
            --build-arg REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }} \
            --build-arg REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} \
            --build-arg REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }} \
            .

      - name: Push Docker Image to Docker Hub
        run: docker push pamitha/ctse-assignment1

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Latest Image
        run: docker pull pamitha/ctse-assignment1

      - name: Stop and Remove Existing Container
        run: docker rm -f ctse-assignment1-container || true

      - name: Run New Container
        run: docker run -d -p 3000:80 --name ctse-assignment1-container pamitha/ctse-assignment1
